"""Keyword search and the retrieval entry point.

Runs against the synthetic specimen, ingested under a filename containing a word no
policy uses, so a match on it can only have come from the filename. The real corpus is
left in place when present; every assertion holds either way.
"""

from pathlib import Path

import pytest

from policyiq.db import get_pool
from policyiq.ingest.pipeline import ingest_pdf
from policyiq.retrieval.keyword import QUESTION_TO_QUERY, keyword_search
from policyiq.retrieval.search import retrieve
from policyiq.retrieval.vector import vector_search

OWNED_NAME = "zanzibarcare-keyword-specimen.pdf"
FILENAME_ONLY_WORD = "zanzibarcare"


@pytest.fixture(scope="module", autouse=True)
def corpus(sample_pdf: Path, tmp_path_factory):
    specimen = tmp_path_factory.mktemp("keyword") / OWNED_NAME
    specimen.write_bytes(sample_pdf.read_bytes())
    result = ingest_pdf(specimen)
    yield result
    with get_pool().connection() as conn:
        conn.execute("DELETE FROM documents WHERE filename = %s", (OWNED_NAME,))


# --- keyword search ------------------------------------------------------------------


def test_every_result_contains_a_word_from_the_question():
    """"cataract" appears in the specimen's waiting-period clause."""
    results = keyword_search("cataract", top_k=5)

    assert results, "the specimen mentions cataract, so there must be a match"
    assert all("cataract" in r.content.lower() for r in results)


def test_any_word_is_enough_to_match():
    """A full question never appears word for word in a policy. Requiring every word -
    the default of Postgres's own websearch_to_tsquery - found almost nothing on real
    questions. "cataract" is in the specimen; the invented word is in no document."""
    assert keyword_search("is cataract covered under quuxplorble", top_k=5)


def test_results_are_ordered_best_first():
    scores = [r.score for r in keyword_search("waiting period for hospitalisation", 10)]

    assert len(scores) >= 2, "need several results, or the ordering check is vacuous"
    assert scores == sorted(scores, reverse=True)


def test_the_filename_is_searchable():
    """The word is only in the filename, so every match must be from this document.
    Punctuation in the name must not hide it: unsplit, the parser reads the whole
    filename as one token."""
    results = keyword_search(FILENAME_ONLY_WORD, top_k=50)

    assert results
    assert {r.filename for r in results} == {OWNED_NAME}


def test_a_hyphenated_word_is_not_turned_into_a_phrase():
    """"pre-existing" is stored as 'pre-exist', 'pre' and 'exist'. The first version of
    the query re-parsed those words, turning 'pre-exist' into a three-word phrase that
    could not match as intended. Every word must stay a separate alternative, so a chunk
    containing only "existing" still matches."""
    with get_pool().connection() as conn:
        query = conn.execute(
            f"SELECT ({QUESTION_TO_QUERY})::text", ("pre-existing disease",)
        ).fetchone()[0]

    assert "<->" not in query, f"a phrase operator crept in: {query}"
    assert keyword_search("pre-existing disease", top_k=5)


def test_a_question_of_only_stop_words_returns_nothing_rather_than_failing():
    assert keyword_search("what is it that they were?", top_k=5) == []


@pytest.mark.parametrize("question", [
    "what's covered?",
    "a & b | !c",
    "cataract:* <-> 'hernia'",
    "'); DROP TABLE chunks; --",
    "",
])
def test_query_syntax_in_the_question_is_treated_as_text(question):
    """Characters that mean something to tsquery must not break the query, and the
    question must never reach the SQL as code."""
    keyword_search(question, top_k=5)

    with get_pool().connection() as conn:
        assert conn.execute("SELECT count(*) FROM chunks").fetchone()[0] > 0


def test_results_carry_the_stored_row():
    result = keyword_search("cosmetic surgery", top_k=1)[0]

    with get_pool().connection() as conn:
        row = conn.execute(
            "SELECT c.document_id, d.filename, c.page_number, c.chunk_index, c.content"
            " FROM chunks c JOIN documents d ON d.id = c.document_id WHERE c.id = %s",
            (result.chunk_id,),
        ).fetchone()

    assert row == (result.document_id, result.filename, result.page_number,
                   result.chunk_index, result.content)


def test_every_chunk_has_its_search_words(corpus):
    """The column is generated by Postgres, so a chunk written by ingestion has it
    without ingestion doing anything. A NULL here would be a chunk keyword search can
    never find."""
    with get_pool().connection() as conn:
        missing, total = conn.execute(
            "SELECT count(*) FILTER (WHERE c.content_tsv IS NULL OR d.filename_tsv IS NULL),"
            " count(*) FROM chunks c JOIN documents d ON d.id = c.document_id"
            " WHERE d.id = %s",
            (corpus.document_id,),
        ).fetchone()

    assert total > 0
    assert missing == 0


# --- the entry point -----------------------------------------------------------------


def test_vector_mode_is_plain_vector_search():
    question = "what treatments are excluded"

    assert retrieve(question, 5, mode="vector") == vector_search(question, 5)


def test_hybrid_mode_returns_distinct_chunks_up_to_top_k():
    results = retrieve("waiting period for cataract", 5, mode="hybrid")

    assert len(results) == 5
    assert len({r.chunk_id for r in results}) == 5


def test_hybrid_keeps_what_only_keyword_search_found():
    """The filename-only word means nothing to an embedding, so vector search returns
    unrelated chunks and only keyword search finds this document.

    Not "first", which is what this test first asserted and got wrong: keyword search's
    1st place and vector search's 1st place both score 1/61, an exact tie, and the lower
    chunk id wins it - usually the real corpus's. What fusion does guarantee is that each
    retriever's top pick survives into a top 2."""
    results = retrieve(FILENAME_ONLY_WORD, 2, mode="hybrid")

    assert OWNED_NAME in {r.filename for r in results}


def test_hybrid_is_best_first():
    scores = [r.score for r in retrieve("claims procedure", 5, mode="hybrid")]

    assert scores == sorted(scores, reverse=True)


def test_a_larger_top_k_extends_the_same_hybrid_ranking():
    """Holds while both calls fuse from the same candidate depth - every top_k up to
    retrieval_candidates."""
    narrow = retrieve("exclusions apply to", 3, mode="hybrid")
    wide = retrieve("exclusions apply to", 6, mode="hybrid")

    assert [r.chunk_id for r in wide][:3] == [r.chunk_id for r in narrow]


def test_an_unknown_mode_is_refused():
    with pytest.raises(ValueError, match="unknown retrieval mode"):
        retrieve("anything", 5, mode="bm25")
